---
AWSTemplateFormatVersion: '2010-09-09'
Description: Enterprise Multi-Region Disaster Recovery Architecture - Master Stack

Parameters:
  VpcCIDR:
    Type: String
    Default: 10.10.0.0/16

Resources:

  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://dr-sheddy.s3.amazonaws.com/vpc.yaml
      Parameters:
        VpcCIDR: !Ref VpcCIDR

  SecurityStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: https://dr-sheddy.s3.amazonaws.com/security.yaml
      Parameters:
        VPCId: !GetAtt VPCStack.Outputs.VPCId

  ALBStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: SecurityStack
    Properties:
      TemplateURL: https://dr-sheddy.s3.amazonaws.com/alb.yaml
      Parameters:
        Subnet1: !GetAtt VPCStack.Outputs.PublicSubnet1
        Subnet2: !GetAtt VPCStack.Outputs.PublicSubnet2
        ALBSG: !GetAtt SecurityStack.Outputs.ALBSG

  ComputeStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: ALBStack
    Properties:
      TemplateURL: https://dr-sheddy.s3.amazonaws.com/compute.yaml
      Parameters:
        Subnet1: !GetAtt VPCStack.Outputs.PublicSubnet1
        Subnet2: !GetAtt VPCStack.Outputs.PublicSubnet2
        EC2SG: !GetAtt SecurityStack.Outputs.EC2SG
        TargetGroup: !GetAtt ALBStack.Outputs.TargetGroup

  DatabaseStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: ComputeStack
    Properties:
      TemplateURL: https://dr-sheddy.s3.amazonaws.com/rds-primary.yaml

