AWSTemplateFormatVersion: '2010-09-09'
Description: DR Starter - Compute and ALB

Parameters:
  ProjectName:
    Type: String
  RegionRole:
    Type: String
    AllowedValues: [PRIMARY, SECONDARY]
  VpcId:
    Type: AWS::EC2::VPC::Id
  PublicSubnetA:
    Type: AWS::EC2::Subnet::Id
  PublicSubnetB:
    Type: AWS::EC2::Subnet::Id
  AppSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id

Conditions:
  IsPrimary: !Equals [!Ref RegionRole, PRIMARY]

Resources:
  AppLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      Type: application
      Subnets:
        - !Ref PublicSubnetA
        - !Ref PublicSubnetB
      SecurityGroups:
        - !Ref AppSecurityGroupId

  AppTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: HTTP
      TargetType: instance
      VpcId: !Ref VpcId
      HealthCheckPath: /

  AppListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref AppTargetGroup
      LoadBalancerArn: !Ref AppLoadBalancer
      Port: 80
      Protocol: HTTP

  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        ImageId: !Sub '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2}}'
        InstanceType: t3.micro
        SecurityGroupIds:
          - !Ref AppSecurityGroupId
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            yum update -y
            yum install -y httpd
            echo "<h1>${ProjectName} ${RegionRole} Region</h1>" > /var/www/html/index.html
            systemctl enable httpd
            systemctl start httpd

  AppAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      MinSize: !If [IsPrimary, '2', '1']
      MaxSize: !If [IsPrimary, '4', '2']
      DesiredCapacity: !If [IsPrimary, '2', '1']
      VPCZoneIdentifier:
        - !Ref PublicSubnetA
        - !Ref PublicSubnetB
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      TargetGroupARNs:
        - !Ref AppTargetGroup

Outputs:
  LoadBalancerDnsName:
    Value: !GetAtt AppLoadBalancer.DNSName
