AWSTemplateFormatVersion: '2010-09-09'
Description: DR Starter - S3 Buckets for Cross-Region Replication

Parameters:
  ProjectName:
    Type: String

Resources:
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-${AWS::Region}-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

Outputs:
  ArtifactBucketName:
    Value: !Ref ArtifactBucket
